/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 11-mar-2020 18:08:54 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `books` CASCADE
;

DROP TABLE IF EXISTS `comment` CASCADE
;

/* Create Tables */

CREATE TABLE `books`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(50) NULL,
	`author` VARCHAR(50) NULL,
	`isbn` VARCHAR(30) NULL,
	`pages` INT NULL,
	`rating` INT NULL,
	CONSTRAINT `PK_books` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `comment`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`body` VARCHAR(500) NULL,
	`book_id` INT NULL,
	`date_creation` DATETIME NULL,
	`update` TIMESTAMP NULL,
	`author` VARCHAR(50) NULL,
	CONSTRAINT `PK_comment` PRIMARY KEY (`id` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `comment` 
 ADD INDEX `IXFK_comment_books` (`book_id` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `comment` 
 ADD CONSTRAINT `FK_comment_books`
	FOREIGN KEY (`book_id`) REFERENCES `books` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
; 
